name: Install and Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build-linux:
    defaults:
      run:
        # Ensures environment gets sourced right
        shell: bash -l {0}
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # setup conda-forge with micromamba
    - name: Setup Python
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
        condarc: |
          channels:
            - conda-forge
            - defaults
        create-args: >-
          python=3.12
        environment-name: prod
        cache-environment: true

    - name: Set cores to get stored in /cores
      run: |
        sudo mkdir /cores
        sudo chmod 777 /cores
        # Core filenames will be of the form executable.pid.timestamp:
        sudo bash -c 'echo "/cores/%e.%p.%t" > /proc/sys/kernel/core_pattern'

    - name: Do Work
      run: |
        set -e
        # Allow core dumps
        ulimit -c unlimited
        sudo systemctl start postgresql.service
        sudo systemctl status postgresql.service -l
        sudo -u postgres psql -c "create role runner with login password 'runner';"
        which psql
        ldd /home/runner/micromamba/envs/prod/bin/psql
        /home/runner/micromamba/envs/prod/bin/psql -l 'postgresql://runner:runner@localhost/postgres?gssencmode=disable'

    #- name: Setup tmate session
    #  if: failure()
    #  uses: mxschmitt/action-tmate@v3

    - uses: actions/upload-artifact@v3
      if: ${{ failure() }}  # Run only if something went wrong
      with:
        name: cores
        path: /cores

